### ISSUE TITLE
pandas bug - columns cannot be sets

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/python-sa-gwdata#24]
**Describe the bug**
Error when using

**To Reproduce**
```python
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sa_gwdata
>>> wells = sa_gwdata.find_wells("5928-203 and also ULE 96")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\devapps\syski\python-sa-gwdata\sa_gwdata\waterconnect_funcs.py", line 34, in find_wells
    session = get_global_session()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\devapps\syski\python-sa-gwdata\sa_gwdata\waterconnect.py", line 85, in get_global_session
    __waterconnect_session = WaterConnectSession()
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\devapps\syski\python-sa-gwdata\sa_gwdata\waterconnect.py", line 128, in __init__
    self.well_cache = pd.DataFrame(columns=set(self.well_id_cols.values()))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\devapps\syski\mambaforge\envs\working\Lib\site-packages\pandas\core\frame.py", line 640, in __init__
    raise ValueError("columns cannot be a set")
ValueError: columns cannot be a set
```

**Expected behavior**
Shouldn't be an exception :-)

**Screenshots**

**Desktop (please complete the following information):**
 - Python version: 
 - python-sa-gwdata version: [e.g. ```>>> import sa_gwdata; sa_gwdata.__version__```]

**Additional context**

**Comment by kinverarity1** [comment]
The fix for this was released in v0.11
